Update breadcrumbs
National-Forestry-Authority/forests pull request #378
Opened 2024-07-11 07:50 UTC by Yash621

updated breadcrumbs navigation structure

demo:

![image](https://github.com/National-Forestry-Authority/forests/assets/58719389/e3005061-cf43-48dd-950a-6488941aba0f)

![image](https://github.com/National-Forestry-Authority/forests/assets/58719389/f410c9d0-0085-4179-85be-1bb13fdffeb6)

2024-07-11 09:58 UTC, peacog requested changes
Hi @Yash621 this is a good start but there is more to do. 

1. Remove the **Back to site** element. It's confusing and not at all useful. Replace it with Home.
2. Change the last element of the breadcrumb, the one that says Edit Asset and Edit Plan, to the name of the asset or plan. With this MR you've added an extra element that's a link to the page you're on. We don't want that because it's confusing. The breadcrumb for a CFR asset should look like this ``Home / Records / Locations / CFRs / Abera``, and Abera should not be clickable.
3. With a breadcrumb trail it should be possible to click on any level of the breadcrumb and see the trail up to that point. For example if you're on Abera the breadcrumb is: ``Home / Records / Locations / CFRs / Abera`` If you click on CFRs that page should have the following breadcrumb: ``Home / Records / Locations / CFRs`` and if you click on Locations you should have ``Home / Records / Locations``
4. The range and sector breadcrumbs should be ``Home / Records / Locations / Sectors`` and ``Home / Records / Locations / Ranges``. Currently they have 'Land' instead of 'Sector' and 'Range'
5. The breadcrumb should work on asset tabs, i.e. the GFW, Management, Logs, Assets tabs on CFRs and the tabs on the other asset types. For example the GFW tab on Abera should have the breadcrumb ``Home / Records / Locations / CFRs / Abera / GFW`` and the Abera element should be a link.
6. The above comments apply to Plans too.

2024-07-11 10:01 UTC, Yash621 commented
> Hi @Yash621 this is a good start but there is more to do.
> 
> 1. Remove the **Back to site** element. It's confusing and not at all useful. Replace it with Home.
> 2. Change the last element of the breadcrumb, the one that says Edit Asset and Edit Plan, to the name of the asset or plan. With this MR you've added an extra element that's a link to the page you're on. We don't want that because it's confusing. The breadcrumb for a CFR asset should look like this `Home / Records / Locations / CFRs / Abera`, and Abera should not be clickable.
> 3. With a breadcrumb trail it should be possible to click on any level of the breadcrumb and see the trail up to that point. For example if you're on Abera the breadcrumb is: `Home / Records / Locations / CFRs / Abera` If you click on CFRs that page should have the following breadcrumb: `Home / Records / Locations / CFRs` and if you click on Locations you should have `Home / Records / Locations`
> 4. The range and sector breadcrumbs should be `Home / Records / Locations / Sectors` and `Home / Records / Locations / Ranges`. Currently they have 'Land' instead of 'Sector' and 'Range'
> 5. The breadcrumb should work on asset tabs, i.e. the GFW, Management, Logs, Assets tabs on CFRs and the tabs on the other asset types. For example the GFW tab on Abera should have the breadcrumb `Home / Records / Locations / CFRs / Abera / GFW` and the Abera element should be a link.
> 6. The above comments apply to Plans too.

yup @peacog thanks for tagging these here, i am aware and currently working on fixing the listed issues, will let you know once it's fixed!

2024-07-17 10:09 UTC, peacog requested changes
Hi @Yash621 I've left you some comments in the code. Also some of the breadcrumbs are wrong:

1. https://forests.ddev.site/assets the last element is 'Pages'
2. On the asset page the asset type should be in plural i.e. CFRs, Sectors, Ranges. That0s because the parent level shows the plural version. They naming should be consistent
3. On assets the breadcrumb is wrong on the Logs and Assets tabs
4. On the plan page the Permissions breadcrumb is Edit-permissions. Change that to Permissions. you can change it in farm_nfa_entity_type_alter and farm_nfa.routing.yml

2024-07-18 08:38 UTC, peacog requested changes
It's working well now @Yash621. I requested a few more changes. 
1. We should always inject services, so we should inject the entityTypeManager. 
2. Some comment improvements
Thanks!

2024-07-18 08:38 UTC, peacog commented on web/modules/custom/farm_nfa/src/BreadcrumbBuilder.php
> +      $asset = is_numeric($asset) ? \Drupal::entityTypeManager()->getStorage('asset')->load($asset) : $asset;
Inject the entityTypeManager. See CommentBreadcrumbBuilder.php and comment.services.yml for an example

2024-07-18 08:38 UTC, peacog commented on web/modules/custom/farm_nfa/src/BreadcrumbBuilder.php
> + * @package Drupal\abv_app
remove @package and change to comment to, for example. Builds the breadcrumbs for assets and plans.

2024-07-18 08:38 UTC, peacog commented on web/modules/custom/farm_nfa/src/BreadcrumbBuilder.php
> +      // Add a link to 'Records' for consistency in breadcrumb.
change this to a @todo to remind us we need to make a Records landing page. for example
// @todo Records should link to a Records landing page, not the home page.

2024-07-18 08:38 UTC, peacog commented on web/modules/custom/farm_nfa/src/BreadcrumbBuilder.php
> +      $links[] = Link::createFromRoute($asset_type . 's', 'farm_nfa.assets.asset', ['asset' => strtolower($asset_type)]);
Explain what we're doing here, e.g.
// The breadcrumb on the assets overview page is plural, so we pluralize
// the fragment on the individual asset page for consistency.

2024-07-18 08:38 UTC, peacog commented on web/modules/custom/farm_nfa/src/BreadcrumbBuilder.php
> +        $links[] = Link::createFromRoute($view_type . 's', '<none>');
As above, explain why we're adding an 's'

2024-07-18 14:50 UTC, closed without merging